import "./globals.css";

import localFont from 'next/font/local'

const xxemeEtage = localFont({
  src: './fonts/XxemeEtage-Regular.woff2',
  variable: '--font-xxeme-etage',
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" className={xxemeEtage.variable}>
      <body className={xxemeEtage.className}>
        {children}
      </body>
    </html>
  );
}
